name: slack-ci
on: 
  push: 
    branches: [ master ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Send slack notification
    - uses: actions/checkout@master
      uses: 8398a7/action-slack@v3
      with: 
        status: ${{ job.status }}
        fields: repo,message,commit,author,eventName,ref,workflow,job,took
      env: s
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()